version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./data:/var/lib/mysql
      
  adminer:
    image: adminer
    ports:
      - 8080:8080
      
  web:
    image: my-django-1.6:1.0
    command: ./entry-point.sh
    restart: always
    links:
      - db:db
    environment:
      DB_HOST: db
    volumes:
      - .:/code
    ports:
      - "8000:8000"