version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    ports:
      - 8080:8080
      
  web:
    image: my-django-1.6:1.0
    command: ./entry-point.sh
    restart: always
    volumes:
      - .:/code
    ports:
      - "80:8000"